import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { createCustomFood, createPlan, createRecipe, listCustomFoods, listRecipes, logRecipeMeal, type CustomFood, type Plan, type Recipe } from '../api/catalog'
import { searchFoods, type Food } from '../api/foods'
import type { MealCategory } from '../api/meals'
import { listGuestCustomFoods, listGuestRecipes, saveGuestCustomFood, saveGuestPlan, saveGuestRecipe, createGuestMealFromPlan } from '../storage/guestStore'
import type { FoodVisionIngredient } from '../api/vision'
import { calculateCarbohydrate, formatCarbohydrate, parseAmountInput, parseServingsInput } from '../lib/carbs'
import { calculateChefTotals, type ChefCalculationInput } from './calculation'
import { ChevronRight, X } from '../components/icons'

type ChefIngredientDraft = { id: string; name: string; uncertain: boolean; confirmed: boolean; food: Food | null; quantity: string }

export type ChefWorkflowProps = {
  guestMode: boolean
  selectedDate: string
  initialName: string
  initialIngredients: FoodVisionIngredient[]
  initialInstructions?: string
  initialNotes?: string
  initialServings?: number
  mealCategory: MealCategory
  onExit: () => void
  onCompleted: (message: string) => void
}

function foodFromCustom(item: CustomFood): Food { return { id: `custom-${item.id}`, name: item.name, originalName: null, brand: item.brand, barcode: null, source: 'custom', sourceId: item.id, availableCarbs100g: item.availableCarbs100g, servingSizeG: item.servingSizeG, imageUrl: null, language: 'hu', country: null, isGeneric: false, isVerified: true, category: 'custom', categoryLabel: 'Saját étel', carbsAvailable: true } }
function sourceLabel(food: Food): string { return food.source === 'custom' ? 'Saját étel' : food.source === 'off' ? 'Open Food Facts' : food.source === 'usda' ? 'USDA' : food.source }
function makeId(): string { return typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}` }

function IngredientMatchRow({ row, guestMode, expanded, onOpen, onChange, onRemove, onConfirm }: { row: ChefIngredientDraft; guestMode: boolean; expanded: boolean; onOpen: () => void; onChange: (patch: Partial<ChefIngredientDraft>) => void; onRemove: () => void; onConfirm: () => void }) {
  const [search, setSearch] = useState(row.name)
  const [manualCarbs, setManualCarbs] = useState('')
  const [manualError, setManualError] = useState<string | null>(null)
  const query = search.trim()
  const searchQuery = useQuery({ queryKey: ['chef-foods', query], queryFn: ({ signal }) => searchFoods(query, signal), enabled: expanded && query.length >= 2, staleTime: 60_000 })
  const customQuery = useQuery({ queryKey: ['chef-custom-foods', query, guestMode], queryFn: () => guestMode ? listGuestCustomFoods(query) : listCustomFoods(query), enabled: expanded && query.length >= 2, staleTime: 30_000 })
  const results = [...(customQuery.data ?? []).map(foodFromCustom), ...(searchQuery.data ?? [])]
  const choose = (food: Food) => { onChange({ food, name: row.name || food.name, confirmed: false }); setSearch(food.name) }
  const createManual = async () => {
    const value = manualCarbs.trim()
    if (!row.name.trim() || !value) { setManualError('Adj meg nevet és CH-t. Az üres CH nem jelent nullát.'); return }
    const carbs = Number(value.replace(',', '.'))
    if (!Number.isFinite(carbs) || carbs < 0 || carbs > 100) { setManualError('Adj meg 0–100 g közötti CH-t 100 g-ra.'); return }
    setManualError(null)
    try {
      const now = new Date().toISOString()
      const saved = guestMode ? { id: makeId(), name: row.name.trim(), brand: null, availableCarbs100g: carbs, dietaryFiber100g: null, servingSizeG: null, notes: 'CHill Chef saját étel', isFavorite: false, createdAt: now, updatedAt: now } satisfies CustomFood : await createCustomFood({ name: row.name.trim(), available_carbs_100g: carbs, notes: 'CHill Chef saját étel' })
      if (guestMode) await saveGuestCustomFood(saved)
      choose(foodFromCustom(saved)); setManualCarbs('')
    } catch (value) { setManualError(value instanceof Error ? value.message : 'A saját étel mentése nem sikerült.') }
  }
  if (!expanded) return <article className="chef-ingredient-row chef-ingredient-row-compact"><button type="button" className="chef-ingredient-summary" onClick={onOpen} aria-expanded="false"><span className={row.uncertain || !row.confirmed ? 'chef-summary-mark warning' : 'chef-summary-mark'}>{row.uncertain ? '!' : row.confirmed ? '✓' : '·'}</span><span className="chef-summary-copy"><strong>{row.name.trim() || 'Névtelen összetevő'}</strong><small>{row.food ? `${row.quantity || '—'} g · ${sourceLabel(row.food)}` : 'Adatforrás és mennyiség szükséges'}</small></span><ChevronRight size={18} /></button></article>
  return <article className="chef-ingredient-row" data-testid={`chef-ingredient-${row.id}`}>
    <div className="chef-ingredient-heading"><label className="field-stack"><span>Összetevő neve</span><input value={row.name} onChange={(event) => { onChange({ name: event.target.value, confirmed: false }); setSearch(event.target.value) }} aria-label={`Összetevő neve ${row.id}`} /></label><button type="button" className="secondary-action compact-action" onClick={onRemove}>Eltávolítás</button></div>
    {row.uncertain && <p className="chef-warning" role="status">Lehetséges összetevő. Erősítsd meg, vagy javítsd a nevet.</p>}
    <label className="field-stack"><span>Kiválasztott adatforrás</span><input value={row.food?.name ?? ''} readOnly placeholder="Válassz találatot vagy adj meg saját ételt" /></label>
    <label className="field-stack"><span>Mennyiség (g)</span><input value={row.quantity} onChange={(event) => onChange({ quantity: event.target.value })} inputMode="decimal" aria-label={`Mennyiség ${row.name}`} /></label>
    {query.length >= 2 && <div className="chef-result-list" aria-label={`${row.name} találatai`}>{searchQuery.isPending || customQuery.isPending ? <p className="search-state">Találatok keresése…</p> : results.length === 0 ? <p className="search-state">Nincs ellenőrzött találat. Adj hozzá saját ételt.</p> : results.map((food) => <button type="button" className={'food-option ' + (row.food?.id === food.id ? 'active' : '')} key={`${food.source}:${food.id}`} onClick={() => choose(food)} disabled={food.availableCarbs100g === null}><span className="food-copy"><strong>{food.name}</strong>{food.originalName && food.originalName !== food.name && <small className="food-source-name">{food.originalName}</small>}<small>{sourceLabel(food)} · {food.availableCarbs100g === null ? 'CH adat nem elérhető' : `${formatCarbohydrate(food.availableCarbs100g)} g CH / 100 g`}</small></span></button>)}</div>}
    <details className="chef-manual-food"><summary>Saját étel hozzáadása ellenőrzött CH-val</summary><label className="field-stack"><span>CH (g / 100 g)</span><input value={manualCarbs} onChange={(event) => setManualCarbs(event.target.value)} inputMode="decimal" placeholder="például 12,5" /></label><button type="button" className="secondary-action" onClick={() => void createManual()}>Saját étel mentése</button></details>
    {manualError && <p className="input-error" role="alert">{manualError}</p>}
    <div className="chef-ingredient-actions"><button type="button" className="secondary-action" onClick={onConfirm} disabled={!row.food || row.confirmed}>{row.confirmed ? 'Összetevő megerősítve' : 'Megerősítem ezt az összetevőt'}</button><button type="button" className="secondary-action" onClick={onOpen}>Bezárás</button></div>
    {row.food && <p className="chef-source-note">Forrás: {sourceLabel(row.food)} · {row.food.availableCarbs100g === null ? 'CH ismeretlen' : `${formatCarbohydrate(row.food.availableCarbs100g)} g / 100 g`}{row.confirmed ? ' · megerősítve' : ' · megerősítés szükséges'}</p>}
  </article>
}

function emptyRow(item?: FoodVisionIngredient): ChefIngredientDraft { return { id: makeId(), name: item?.name ?? '', uncertain: item?.uncertain ?? false, confirmed: false, food: null, quantity: '' } }

export function ChefWorkflow({ guestMode, selectedDate, initialName, initialIngredients, initialInstructions = '', initialNotes = '', initialServings = 1, mealCategory, onExit, onCompleted }: ChefWorkflowProps) {
  const [name, setName] = useState(initialName); const [instructions, setInstructions] = useState(initialInstructions); const [notes, setNotes] = useState(initialNotes); const [servings, setServings] = useState(String(initialServings)); const [rows, setRows] = useState<ChefIngredientDraft[]>(() => initialIngredients.length > 0 ? initialIngredients.map(emptyRow) : [emptyRow()]); const [activeRowId, setActiveRowId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [status, setStatus] = useState<string | null>(null); const [completionError, setCompletionError] = useState<string | null>(null); const [savedRecipe, setSavedRecipe] = useState<Recipe | null>(null); const [completion, setCompletion] = useState(false); const [completedActions, setCompletedActions] = useState<Partial<Record<'recipe' | 'log' | 'plan', boolean>>>({}); const [recipes, setRecipes] = useState<Recipe[]>([])
  useEffect(() => { let active = true; void (guestMode ? listGuestRecipes() : listRecipes()).then((items) => { if (active) setRecipes(items) }).catch(() => { /* optional suggestions */ }); return () => { active = false } }, [guestMode])
  const validRows = rows.map((row): ChefCalculationInput => ({ quantityG: parseAmountInput(row.quantity), availableCarbs100g: row.food?.availableCarbs100g ?? null })); const calculation = calculateChefTotals(validRows); const servingNumber = parseServingsInput(servings); const missingConfirmation = rows.some((row) => row.uncertain || !row.confirmed); const invalidQuantity = validRows.some((row) => row.quantityG === null); const canSave = name.trim().length > 0 && rows.length > 0 && servingNumber !== null && !missingConfirmation && !invalidQuantity && rows.every((row) => row.food?.availableCarbs100g !== null && row.food !== null) && calculation.complete && calculation.totalCarbsG !== null
  const recipeSuggestions = recipes.filter((recipe) => rows.some((row) => row.name.trim() && recipe.ingredients.some((ingredient) => String(ingredient.snapshot.name ?? '').toLocaleLowerCase().includes(row.name.trim().toLocaleLowerCase())))).slice(0, 3)
  const updateRow = (id: string, patch: Partial<ChefIngredientDraft>) => setRows((current) => current.map((row) => row.id === id ? { ...row, ...patch } : row)); const removeRow = (id: string) => setRows((current) => current.length > 1 ? current.filter((row) => row.id !== id) : current)
  const handleExit = () => { const hasDraft = !savedRecipe && (name !== initialName || rows.some((row) => row.name.trim() || row.food || row.quantity)); if (hasDraft && !window.confirm('Elveted a megkezdett receptet?')) return; onExit() }
  const save = async (mode: 'recipe' | 'log' | 'plan') => {
    if (!savedRecipe && (!canSave || servingNumber === null || calculation.totalCarbsG === null)) { setError('Minden összetevőt, forrást, grammot és adagot ellenőrizni kell mentés előtt.'); return }
    if (savedRecipe && completedActions[mode]) { setCompletion(true); setStatus(mode === 'log' ? 'Ez a recept már szerepel a naplóban.' : mode === 'plan' ? 'Ez a recept már szerepel a tervben.' : 'Ez a recept már el van mentve.'); return }
    setBusy(true); setError(null); setCompletionError(null); setStatus(null); let recipe = savedRecipe
    try {
      if (!recipe) {
        const totalWeight = validRows.reduce((sum, row) => sum + (row.quantityG ?? 0), 0); const ingredientPayload = rows.map((row, index) => ({ food_id: row.food?.source === 'custom' ? undefined : row.food?.id, custom_food_id: row.food?.source === 'custom' ? row.food.sourceId : undefined, quantity_g: validRows[index].quantityG as number })); const now = new Date().toISOString()
        if (guestMode) { const recipeId = makeId(); recipe = { id: recipeId, name: name.trim(), instructions: instructions.trim() || null, prepMinutes: null, notes: notes.trim() || 'CHill Chef által ellenőrzött összetevőkből', servings: servingNumber as number, totalWeightG: totalWeight, totalCarbsG: calculation.totalCarbsG as number, carbsPerServingG: (calculation.totalCarbsG as number) / (servingNumber as number), carbsPer100gCookedG: null, isFavorite: false, ingredients: rows.map((row, index) => ({ id: makeId(), foodId: row.food?.source === 'custom' ? null : row.food?.id ?? null, customFoodId: row.food?.source === 'custom' ? row.food.sourceId : null, quantityG: validRows[index].quantityG ?? 0, calculatedCarbsG: calculateCarbohydrate(validRows[index].quantityG ?? 0, row.food?.availableCarbs100g ?? null) ?? 0, snapshot: { name: row.food?.name, source: row.food?.source, source_id: row.food?.sourceId, available_carbs_100g: row.food?.availableCarbs100g }, position: index })), createdAt: now, updatedAt: now }; await saveGuestRecipe(recipe) } else recipe = await createRecipe({ name: name.trim(), servings: servingNumber, total_weight_g: totalWeight, instructions: instructions.trim(), notes: notes.trim() || 'CHill Chef által ellenőrzött összetevőkből', ingredients: ingredientPayload }); setSavedRecipe(recipe)
      }
      if (mode === 'log') { if (guestMode) await createGuestMealFromPlan({ id: makeId(), planDate: selectedDate, mealCategory, foodId: null, customFoodId: null, recipeId: recipe.id, quantity: 1, quantityUnit: 'servings', plannedCarbsG: recipe.carbsPerServingG, snapshot: { name: recipe.name, source: 'recipe', source_id: recipe.id }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, selectedDate); else await logRecipeMeal(recipe.id, { quantity: 1, quantity_unit: 'servings', local_date: selectedDate, meal_category: mealCategory, idempotency_key: `chef-log-${recipe.id}-${selectedDate}` }) }
      if (mode === 'plan') { const plan: Plan = { id: makeId(), planDate: selectedDate, mealCategory, foodId: null, customFoodId: null, recipeId: recipe.id, quantity: 1, quantityUnit: 'servings', plannedCarbsG: recipe.carbsPerServingG, snapshot: { name: recipe.name, source: 'recipe', source_id: recipe.id }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; if (guestMode) await saveGuestPlan(plan); else await createPlan({ plan_date: selectedDate, meal_category: mealCategory, recipe_id: recipe.id, quantity: 1, quantity_unit: 'servings' }) }
      const message = mode === 'log' ? 'A recept elmentve és a naplóba került.' : mode === 'plan' ? 'A recept elmentve és a tervbe került.' : 'A recept elmentve.'; setCompletedActions((current) => ({ ...current, recipe: true, [mode]: true })); setCompletion(true); setStatus(message); onCompleted(message)
    } catch (value) { const message = value instanceof Error ? value.message : mode === 'log' ? 'A naplózás nem sikerült.' : mode === 'plan' ? 'A terv mentése nem sikerült.' : 'A recept mentése nem sikerült.'; if (recipe) { setSavedRecipe(recipe); setCompletion(true); setCompletionError(message) } else setError(message) } finally { setBusy(false) }
  }
  if (completion && savedRecipe) return <section className="chef-workflow chef-completion" data-testid="chef-completion" aria-label="Chef befejezése"><div className="chef-header"><div><p className="eyebrow">CHill Chef · 7 / 7 Befejezés</p><h3>Recept mentve ✓</h3></div><button type="button" className="close-button" onClick={handleExit} disabled={busy} aria-label="Chef bezárása"><X size={18} /></button></div><div className="chef-completion-summary"><strong>{savedRecipe.name}</strong><span>{formatCarbohydrate(savedRecipe.carbsPerServingG)} g CH / adag</span><small>{savedRecipe.servings} adag · {selectedDate} · {mealCategory === 'other' ? 'Egyéb' : mealCategory}</small></div>{completionError && <p className="input-error" role="alert">{completionError} A recept már el van mentve; csak ezt a műveletet próbáld újra.</p>}{status && <p className="goal-help" role="status">{status}</p>}<div className="chef-actions"><button className="confirm-button" onClick={() => void save('log')} disabled={busy}>Naplózom</button><button className="secondary-action" onClick={() => void save('plan')} disabled={busy}>Hozzáadom a tervhez</button><button className="secondary-action" onClick={() => setCompletion(false)} disabled={busy}>Recept szerkesztése</button><button className="secondary-action" onClick={handleExit} disabled={busy}>Kész</button></div></section>
  return <section className="chef-workflow" aria-label="CHill Chef munkafolyamat"><div className="chef-header"><div><p className="eyebrow">CHill Chef · 6 / 7 Összetevők</p><h3>Recept ellenőrzése</h3></div><button type="button" className="close-button" onClick={handleExit} disabled={busy} aria-label="Chef bezárása"><X size={18} /></button></div><p className="goal-help">A recept csak ellenőrzött adatforrásból és az általad megadott mennyiségből kap CH-értéket.</p><label className="field-stack"><span>Recept neve</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field-stack"><span>Adagok száma</span><input value={servings} onChange={(event) => setServings(event.target.value)} inputMode="decimal" aria-invalid={Boolean(servings.trim() && servingNumber === null)} /></label><label className="field-stack"><span>Étkezési kategória</span><select value={mealCategory} disabled><option value={mealCategory}>{mealCategory === 'breakfast' ? 'Reggeli' : mealCategory === 'lunch' ? 'Ebéd' : mealCategory === 'dinner' ? 'Vacsora' : mealCategory === 'morning_snack' ? 'Tízórai' : mealCategory === 'afternoon_snack' ? 'Uzsonna' : 'Egyéb'}</option></select></label><label className="field-stack"><span>Elkészítési útmutató</span><textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} rows={4} placeholder="A javaslat ellenőrzött lépései" /></label><label className="field-stack"><span>Megjegyzés</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={2} placeholder="Opcionális" /></label>
    <div className="chef-ingredients"><div className="section-heading"><div><p className="eyebrow">6 / 7 Összetevők</p><h4>{rows.filter((row) => row.confirmed && !row.uncertain).length} / {rows.length} kész</h4></div><button type="button" className="secondary-action compact-action" onClick={() => { const row = emptyRow(); setRows((current) => [...current, row]); setActiveRowId(row.id) }}>Összetevő hozzáadása</button></div>{rows.map((row) => <IngredientMatchRow key={row.id} row={row} guestMode={guestMode} expanded={activeRowId === row.id || (activeRowId === null && row.id === rows[0]?.id && !rows.some((candidate) => candidate.confirmed))} onOpen={() => setActiveRowId(activeRowId === row.id ? null : row.id)} onChange={(patch) => updateRow(row.id, patch)} onRemove={() => removeRow(row.id)} onConfirm={() => { updateRow(row.id, { uncertain: false, confirmed: true }); setActiveRowId(row.id) }} />)}</div>
    {recipeSuggestions.length > 0 && <section className="chef-recipe-suggestions" aria-label="Meglévő receptjavaslatok"><p className="eyebrow">Meglévő receptjavaslatok</p>{recipeSuggestions.map((recipe) => <div className="chef-recipe-suggestion" key={recipe.id}><strong>{recipe.name}</strong><small>{formatCarbohydrate(recipe.carbsPerServingG)} g CH / adag · ellenőrzött katalógusadat</small></div>)}</section>}
    <div className="chef-summary"><p className="eyebrow">Ellenőrzött CH-összesítés</p>{servingNumber === null ? <><strong>Az adagszámot ellenőrizni kell.</strong><small>Például 0,5 vagy 2 adagot adhatsz meg.</small></> : calculation.complete ? <strong>{formatCarbohydrate(calculation.totalCarbsG ?? 0)} g CH összesen · {formatCarbohydrate((calculation.totalCarbsG ?? 0) / servingNumber)} g/adag</strong> : <><strong>A teljes CH még nem számítható.</strong><small>Ismert rész: {formatCarbohydrate(calculation.knownCarbsG)} g CH / {formatCarbohydrate(calculation.knownMassG)} g. Hiányzó adatok: {calculation.missingCount}.</small></>}</div>
    {error && <p className="input-error" role="alert">{error}</p>}{status && <p className="goal-help" role="status">{status}</p>}<div className="chef-actions"><button type="button" className="confirm-button" onClick={() => void save('recipe')} disabled={!canSave || busy}>Recept mentése</button><button type="button" className="confirm-button" onClick={() => void save('log')} disabled={!canSave || busy}>Mentés és naplózás</button><button type="button" className="secondary-action" onClick={() => void save('plan')} disabled={!canSave || busy}>Mentés és tervezés</button></div>
  </section>
}
